---
run:
  timeout: 120s
  skip-dirs:
    - pkg/generated

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  gci:
    local-prefixes: github.com/charithe/menshen

  gofumpt:
    extra-rules: true

  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true


linters:
  enable:
    - asciicheck
    - bodyclose
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - goconst
    - gocritic
    - godot
    - gofumpt
    - goimports
    - goheader
    - gomnd
    - gosec
    - ifshort
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
  disable:
    - cyclop
    - depguard
    - dogsled
    - exhaustivestruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - golint
    - gomodguard
    - goprintffuncname
    - interfacer
    - lll
    - maligned
    - nlreturn
    - paralleltest
    - stylecheck
    - testpackage
    - wrapcheck
    - wsl

issues:
  max-same-issues: 30

  fix: true

  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - scopelint
